NADCON5-ng: src/BinSource/xyz2b.f File Reference
xyz2b.f File Reference
Functions/Subroutines
program xyz2b
Part of the NADCON5 NADCON5 Core Library , Converts GMT *.grd to a *.b NADCON style grid file.
subroutine put1 (ival, gla, glo, h, nla, nlo, glamn, dgla, glomn, dglo, iclp)
subroutine put2 (val, gla, glo, z, nla, nlo, glamn, dgla, glomn, dglo, iclip)
subroutine w1 (lout, h, nla, nlo, glamn, dgla, glomn, dglo)
subroutine w2 (lout, z, nla, nlo, glamn, dgla, glomn, dglo)
logical function makpos (glon)
Function/Subroutine Documentation
logical function makpos (glon)
Definition at line 248 of file xyz2b.f.
 *** insure longitude is positive  (single precision)
       makpos=.false.
     1 if(glon.lt.0.d0) then
         glon=glon+360.d0
         makpos=.true.
         go to 1
       endif
     2 if(glon.ge.360.d0) then
         glon=glon-360.d0
         go to 2
       endif
       return
subroutine put1 (ival, real*4 gla, real*4 glo, integer, dimension(nla,nlo) h, nla, nlo, glamn, dgla, glomn, dglo, iclp)
Definition at line 181 of file xyz2b.f.
Referenced by xyz2b().
 *** load value into grid
       implicit double precision(a-h,o-z)
       real*4  val,gla,glo
       integer h(nla,nlo)
       i=idnint((gla-glamn)/dgla)+1
       if(i.lt.1.or.i.gt.nla) then
         iclp=iclp+1
         return
       endif
       j=idnint((glo-glomn)/dglo)+1
       if(j.lt.1.or.j.gt.nlo) then
         iclp=iclp+1
         return
       endif
       h(i,j)=ival
       return
subroutine put2 (real*4 val, real*4 gla, real*4 glo, real*4, dimension(nla,nlo) z, nla, nlo, glamn, dgla, glomn, dglo, iclip)
Definition at line 203 of file xyz2b.f.
Referenced by xyz2b().
 *** load value into grid
       implicit double precision(a-h,o-z)
       real*4 z(nla,nlo),val,gla,glo
       i=idnint((gla-glamn)/dgla)+1
       if(i.lt.1.or.i.gt.nla) then
         iclip=iclip+1
         return
       endif
       j=idnint((glo-glomn)/dglo)+1
       if(j.lt.1.or.j.gt.nlo) then
         iclip=iclip+1
         return
       endif
       z(i,j)=val
       return
subroutine w1 (lout, integer, dimension(nla,nlo) h, nla, nlo, glamn, dgla, glomn, dglo)
Definition at line 224 of file xyz2b.f.
Referenced by xyz2b().
 *** write records south to north (elements are west to east)
       implicit double precision(a-h,o-z)
       integer h(nla,nlo)
       do 1 i=1,nla
     1 write(lout) (h(i,j),j=1,nlo)
       return
subroutine w2 (lout, real*4, dimension(nla,nlo) z, nla, nlo, glamn, dgla, glomn, dglo)
Definition at line 236 of file xyz2b.f.
Referenced by xyz2b().
 *** write records south to north (elements are west to east)
       implicit double precision(a-h,o-z)
       real*4 z(nla,nlo)
       do 1 i=1,nla
     1 write(lout) (z(i,j),j=1,nlo)
       return