/**
\file dirs.inc

\brief Documentation Stubs for Folders and Files
*/

/**
\ingroup doers

\dir src
\brief Folder containing the \ref doers and subfolders \ref Code/Subs and \ref Code/BinSource
*/


/**
\ingroup core

\dir src/BinSource
\brief Folder containing \ref core Programs
*/


/**
\ingroup core

\dir src/Subs
\brief Folder containing \ref core Subroutines
*/




/**
\dir docs
\brief Documentation Folder
*/

/**
\dir docs/modules
\brief Internal Document Structure (Groupings and Extra Documentation for folders)
*/

/**
\dir docs/pages
\brief Extra Documentation Pages
*/

/**
\dir data
\brief Data Folder
*/
/**
\dir data/Control
\brief Control Data for 
*/

