/**
\defgroup doers NADCON5 Build Pipeline
\brief Programs which perform the generation of `GMT` batch scripts and the creation of output files using \ref core and \ref helpers

The elements described here are the "doers", programs that construct the output using elements of \ref core

*/

/**
\ingroup doers

\dir src
\brief Folder containing the \ref doers and subfolders \ref Code/Subs and \ref Code/BinSource
*/




/**
\defgroup core NADCON5 Core Library
\brief Programs and Functions which are responsible for computing the grid transformations used to build NADCON5

The programs here can be considered "Library" Programs, or functions, which do the raw work of computing various transformations and conversions from `*.b` NADCON binary grid to a `GMT` style `*.grd` 

*/

/**
\ingroup core

\dir src/BinSource
\brief Folder containing \ref core Programs
*/

/**
\ingroup core

\dir src/Subs
\brief Folder containing \ref core Subroutines
*/





/**
\defgroup build Build System

Makefile Documentation

*/

/**
\ingroup build

\file Makefile
*/


/**
\ingroup build
\defgroup source-compilation Compilation
*/