/**
\file groups.inc
\brief Documentation Stubs for Groups (Modules)
*/

/**
\defgroup doers NADCON5 Build Programs
\brief Programs which perform the generation of `GMT` batch scripts and the creation of output files using \ref core and \ref helpers

The elements described here are the "doers", programs that construct the output using elements of \ref core

*/




/**
\defgroup core NADCON5 Core Library
\brief Programs and Functions which are responsible for computing the grid transformations used to build NADCON5

The programs here can be considered "Library" Programs, or functions, which do the raw work of computing various transformations and conversions from `*.b` NADCON binary grid to a `GMT` style `*.grd` 

*/






/**
\defgroup nc5data Python Data Inspection Library
\brief Python Wrapper Library around the data files provided by NADCON5.

That is, this is a pythonic wrapper *for the data itself*

*/